apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:aDxtpQ==,iv:Sd2yzBBdKrOU2795T2xzOF9KybXhTblqQzhQVBm8DLU=,tag:GarvZcImXMQx3iOx0in8tA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:2NYZGzzQvaaJL/BC,iv:d5WZwpaf+rSNvaWpB/iOxKrNqwBNmElPLLHgdDuFSGA=,tag:+YTb4W7Tx6BKo1iewWlcRw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age195a0t06ss37kl5uj94kr5vhkasy4fxzwp5hq7xlx2ezxl94lfseqyq2cf9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYUNvTHAvbDNpck1QbFRa
            RnlINnRvcGxOT0lwSzJuZ2dPQlBQRDhJbFhjCnFOVDZxUllidE1GdXdabXNTdjhK
            VEhXenBreFNBZkdSbEwyb3NmSjFmNkEKLS0tIFplQ0Fmc0lPeDFrd1c3WVBQNHBU
            YmFEVXhiTDR5RVhibmptaVo1cFQ2bFEKVThsewH30OMwwF6Y1zZNIfSM5QWnXvE7
            i4GcEsSeppAyWMoQXGLzeA0utr5ZVGj3Xuk9nQ65xuHvCjw2id9Q9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T23:57:52Z"
    mac: ENC[AES256_GCM,data:7F607tingw49q9qI9Jl+guUYPnAgMf3zc8SLWxLvqLW585qsV4I4OG9lUc0Xler1HhsQOkLp5HqSvcxIQT8ybj4x4ia+a9uZ4l4P3NTri1AEHy5qHy7MYka91LF9rR1OJUdFBofznn5YW1niubgg6DQEI/4cPX+uVrXjMTFD/y8=,iv:dKUcRBiYigoCv/Omnp6qEFU6wJ9GxxwtDd/dR8sqnp8=,tag:XlZGDKC9w94x7AvzUZ54ZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
