apiVersion: v1
data:
    password: ENC[AES256_GCM,data:hfCVOcP7vpblRCzf,iv:ncDFYNNjOuX8kCTGJDkuosPjeTs/P1jeWzXFb0933Es=,tag:aBnNBWPPedIpiwJOODi2mg==,type:str]
    user: ENC[AES256_GCM,data:3oBLm58OOGc=,iv:5qymbl+m/4LEqotJpeCRAXp9twP/QT2gz+0ilcaIr0g=,tag:l3g8U42HZmcuspzBQx8cag==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age195a0t06ss37kl5uj94kr5vhkasy4fxzwp5hq7xlx2ezxl94lfseqyq2cf9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NHdLQy9KQkpMNmdOR3Zy
            a3ljN290WVE1ZHdYVlQvTnNQdk1IMmJueGpjCnR1TWYrUGVCZGRRQTg0RWVoYTlR
            MzIwV3hIUE5SRDY1K3dFYW1QaTRCbVUKLS0tIGI5ekVLNmdudUxsb0QzTWk4U0xp
            eGozL0xMOE1uY0RYSk9VOXRUYkRBdG8K8XCyEIVo/n1YcsvNIPXzt60jWbBpRulm
            wWEQOD1I6HdQOFSCv40NNw3WZxL7QFKFI2bf5ltvGxRPSGXBHW/nFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T20:13:29Z"
    mac: ENC[AES256_GCM,data:IIcwCiA1HqfraJVGbMRuNimrNwctoOZxu5j8B/drNh5V2+2l7bcf3fzxaU56uVgu1r7pX06fS+zef2W0zzOWljHgS7G17/8iNAdWlxWMphSqQNjE4SVXuuzHLZdkaf+BOr1/92GVLMXFCEzCzgAbmdOZz+Ha06sWbrwbvn5v3SY=,iv:lr7rjqCD9cpigpG7qHxsqv+tdBgymE+plb5TCR9KUOI=,tag:0RzyQLQ9ibrOjscnq6HxDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
